services:
  armada:
    build: .
    ports:
      - "18080:8080"
    command: ["-listen", ":8080", "-no-gpio"]
    volumes:
      - ./docker-data:/etc/armada
    environment:
      ARMADA_PASSWORD: ${ARMADA_PASSWORD:-}
